version: "3.7"

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
networks:
  public:
    driver: bridge
  private:
    driver: bridge
  db:
    driver: bridge

services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    networks:
      - db
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.2
    networks:
      - db
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5433:5432"
  Keycloak_ifood:
    container_name: Keycloak_ifood
    image: quay.io/keycloak/keycloak:15.0.2
    networks:
      - public
      - db
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.27
    networks:
      - private
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus_ifood:
    #    image: prom/prometheus:v2.30.3
    image: prometheus-ifood
    container_name: prometheus_ifood
    networks:
      - default
      - private
    volumes:
      #      - /etc/prometheus:/config
      - prometheus-data:/prometheus
    #    command: --config.file=/config/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana_ifood:
    image: grafana/grafana:6.5.0
    container_name: grafana_ifood
    networks:
      - private
      - public
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always

  artemis_ifood:
    image: vromero/activemq-artemis:2.16.0-alpine
    container_name: artemis_ifood
    ports:
      - "8161:8161"
      - "5672:5672"
      - "61616:61616"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin

  mongodb_ifood:
    image: mongo:5.0.3-focal
    container_name: mongodb_ifood

    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pedido
      MONGO_INITDB_ROOT_PASSWORD: pedido
      MONGO_INITDB_DATABASE: pedido


  zookepper:
    image: debezium/zookeeper:1.7.0.Final
    container_name: zookepper_container
    ports:
      - "2181:8181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: debezium/kafka:1.7.0.Final
    container_name: kafka_container
    ports:
      - "9092:9092"
    links:
      - zookepper
    environment:
      - ZOOKEEPER_CONNECT=zookepper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092

  kafdrop:
    image: obsidiandynamics/kafdrop:3.28.0-SNAPSHOT
    container_name: kafdrop_container
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka
